name: Build-Win-x64-SingleFile

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET SDK 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore TrayPasswordGenerator.csproj

    - name: Publish (single exe, no trimming)
      run: >
        dotnet publish TrayPasswordGenerator.csproj
        -c Release
        -r win-x64
        --self-contained true
        /p:PublishSingleFile=true
        /p:PublishTrimmed=false

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: TrayPasswordGenerator
        path: bin\Release\net8.0-windows\win-x64\publish\TrayPasswordGenerator.exe
